config/routes.rb
ToGo::Application.routes.draw do
 devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
 
  root :to => "main#index"
  get "main/home"
  post 'events/create', as: 'event_create'
  get 'events/join/:id', to: 'events#join', as: 'join'
  get 'events/event/:id', to: 'events#event' , as: 'event'
  get 'main/new_event'
  get "main/events"
  get "main/people"
  get "main/profile"
  get "main/results"
  get "main/map"
  get "main/chat"
  get "main/events"
  get "main/Myfavorite"

  

end

app/models/events.rb
class Events < ActiveRecord::Base
end

app/models/people_actions.rb
class PeopleActions < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
         
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
  user = User.where(:provider => auth.provider, :uid => auth.uid).first
  unless user
    user = User.create(name:auth.extra.raw_info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         password:Devise.friendly_token[0,20]
                         )
  end
  user
end

def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    unless user
        user = User.create(name: data["name"],
             email: data["email"],
             password: Devise.friendly_token[0,20]
            )
    end
    user
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
 private
  def after_sign_in_path_for(resource_or_scope)
   '/main/home' 
  end
  def after_sign_out_path_for(resource_or_scope)
   root_path
  end
  
  
  end

app/controllers/events_controller.rb
require 'date'

class EventsController < ApplicationController
  ACTION_TYPES ={:request => 0, :invite => 1, :going => 2, :maybe => 3, :not_going => 4, :follow => 5 }

  def event
    @event = Events.find(params[:id])
    @people_going = PeopleActions.where(e_id: @event.id, action: ACTION_TYPES[:going]).all 
    # render text: "#{@people_going} and #{@event} and #{tmp}"
  end

  def join
    user_id = 1234
    event = Events.find(params[:id])
    action = PeopleActions.find_by u_id: user_id, e_id: event.id
    if(action == nil)
      action = PeopleActions.new(u_id: user_id, e_id: event.id, action: ACTION_TYPES[:going])
      action.save
    else
    end
    # render text: ACTION_TYPES[:going]
    redirect_to event_path(event.id)
  end

  def create
    @event = Events.new(event_params)
    @event.save
    redirect_to event_path(@event.id)
  end

  private

  def event_params
    clone_params = params.deep_dup
    clone_params[:new_event].merge!(:user_id => 1234)
    s_date = Date.strptime(clone_params[:new_event][:s_date] , "%m/%d/%Y").to_s
    clone_params[:new_event][:s_date] = s_date
    clone_params.require(:new_event).permit(:title, :description, :location, :s_date, :e_date, :visibility, :user_id)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def home
    @events = Events.all
  end

  def map
  end

  def profile
   respond_to do |format|
      format.html
      format.js
    end
  end

  def chat
    respond_to do |format|
      format.html
      format.js
    end
  end

  def results

  end

  def people
    respond_to do |format|
      format.html
      format.js
    end
  end

  def event
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new_event
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/main_helper.rb
module MainHelper
    def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/events/event.html.erb
<%= render partial: "/main/title" %>
<% event = @event %>
<div style="width: 960px;margin:auto;padding: 10px">
	<div>
		<div style="margin: 5px;">
			<%= link_to "<=back", "/main/home/" %>
		</div>
		<div style="font-size: 25px">
			<%= event.title %> <a href="/main/events/" style="font-size: 14px;" class="circle tag">#Surfing</a>
			<a href="/main/events/" style="font-size: 14px;" class="circle tag">#Sport</a>
		</div>
		<div>
			invided by Norman
		</div>
	</div>
	<div>
		<div style="width: 192px; float: left;margin-top: 10px;height:100%">
			<% if @people_going.count > 0 %>
			<div style="border-top: 1px solid #999;">
				Goging
				<div style="padding-left: 10px;">
					<% @people_going.each do |people| %>
					<div>
						<%= people.u_id %>
					</div>
					<% end %>
				</div>
			</div>
			<% end %>
			<div style="border-top: 1px solid #999;">
				Maybe
				<div style="padding-left: 10px;">
					<div>
						Norman
					</div>
					<div>
						A-man
					</div>
				</div>
			</div>
			<div style="border-top: 1px solid #999;">
				Invided
				<div style="padding-left: 10px;">
					<div>
						Norman
					</div>
					<div>
						A-man
					</div>
				</div>
			</div>
		</div>
		<div style="float: left;margin-top: 10px;border-left: 1px solid #999;border-top:1px solid #999;">
			<div style="width: 513px">
				<ul style="padding: 10px 10px 0px;">
					<li style="height: 28px;border-bottom: 1px solid #999;">
						<ul>
							<li>
								<div style="zoom: 1;float: left; font-size: 13px;margin-right: 20px;">
									<img style="vertical-align:text-top;" src="https://fbstatic-a.akamaihd.net/rsrc.php/v2/yJ/r/UmLbGfwEuH6.png" title="When" width="16" height="16">
									<a href="/events/calendar/2013/September/9" style="text-decoration: none;"><%= event.s_date %></a>
								</div>
							</li>
							<li>
								<div style="zoom: 1;float: left; font-size: 13px;margin-right: 20px;border-left: 1px solid #999; padding-left: 10px;">
									<img style="vertical-align:text-top;" src="https://fbstatic-a.akamaihd.net/rsrc.php/v2/y0/r/MY8128-Z6ed.png" title="Time" width="16" height="16">
									<a href="/ajax/events/edit_form.php?fbid=304759993001019&amp;focus=time" style="text-decoration: none;">What time?</a>
								</div>
							</li>
						</ul>
					</li>
					<li style="margin-top: 10px;">
						<table>
							<tr>
								<td> <%= event.description %> </td>
							</tr>
						</table>
					</li>
				</ul>
				<div style="float: left;position: relative;margin-top: 10px;border-bottom:1px solid #999;">
					<div style="padding: 0px 10px 10px;">
						<img alt="Norman Chen" src="/assets/map.jpg">
						<div style="position: absolute;top: 50px;width: 503px;">
							<div style="margin: auto;width: 340px;position: relative;margin: auto;">
								<input id="q" name="q" type="text" style="width: 100%">
							</div>
						</div>
					</div>
				</div>
			</div>
			<div style="margin-left: 10px;margin-top:10px;border-bottom; 1px solid #999;">
				<ul>
					<li>
						<div style="float: left;margin-right: 20px;font-size: 13px;margin-top: 10px;">
							<a href="#123">Write Post</a>
						</div>
					</li>
					<li>
						<div style="float: left;margin-right: 20px;font-size: 13px;margin-top: 10px;">
							<a href="#123">Add Photo / Video</a>
						</div>
					</li>
					<li>
						<div style="float: left;margin-right: 20px;font-size: 13px;;margin-top: 10px;">
							<a href="#123">Ask Question</a>
						</div>
					</li>
					<li>
						<textarea id="q" name="q" type="text" style="width: 95%;overflow: hidden;resize: none;height: 16px;margin-top: 10px;">
					</textarea>
					</li>
				</ul>

				<ul style="vertical-align: text-top;">
					<% for i in 1..10 %>
					<li style="font-size: 18px;margin-top: 10px;border-top: 1px solid #999; padding-top:5px">
						<img alt="Profile" src="/assets/profile.jpg" style="height: 20px; float:left;">
						<div style="font-size: 13px;margin-left: 25px;">
							<a href="#Norman_Chen">Norman Chen</a>
							<div style="margin: 10px 0px 10px;">
								ajsdlkfjlksajfdkljlfajshdfajslfdjllasjdlkfjlkajfl
								<br>
								jalskdjfklajsdlfajsdkfl
							</div>
							<span style="font-size: 11px;"> <span> Like </span> <span>Comment</span> <span>Unfollow</span> <span> <%= Time.current() %></span></span>
						</div>
					</li>
					<% end %>
				</ul>

			</div>
		</div>
		<div style="clear: both;padding: 0 20px 12px;"></div>
		<div style="width: 100%;border-top: 1px solid #999;">
			We love here.
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>iToGo</title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
		<%= javascript_include_tag "jquery.jscrollpane.min" => true %>
		<%= stylesheet_link_tag "jquery.jscrollpane" => true%>
		<script type="text/javascript" src="http://code.jquery.com/jquery-1.8.2.js"></script>
		<link href='http://fonts.googleapis.com/css?family=Londrina+Shadow' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<%= yield %>

	</body>
</html>

app/views/main/Myfavorite.html.erb
<%= javascript_include_tag "main" %>
<div class="top_title">
	<div class="title_container">
		<span id="text2">ITOGO</span>
		<div class="logout">
			log out
		</div>
	</div>
</div>
<div class="container">
	<div class="left_column">
		<div class="top_profile">
			<%= image_tag("profile.jpg", :alt => "Norman Chen", :size => "70x70", :class => "profile_photo") %>
			<div class="profile_name">
				Norman Chen
				<br>
				Edit your profile
			</div>
		</div>
		<div class="chat">
				<div class="circle">
					3
				</div>
			<%= image_tag("iconChat.png", :alt => "chat") %> <%= link_to "Chat","/main/chat",class:"decoration" %>	
		</div>

		<div class='events'>
			<%= image_tag("events.png", :alt => "chat") %><%= link_to "Events","/main/events",class:"decoration" %>
		</div>
		<div class="favorite">
			<%= image_tag("fav.png", :alt => "chat") %><%= link_to "My favorite","/main/Myfavorite",class:"decoration" %>
		</div>
		<br>
		<br>
		<br>
		<br>
		<br>
		<div class="self_info">
		 練習自我介紹中，請勿打擾．<br>
		 哥寫的不是程式．<br>
		 哇嗚！！！<br>
		 <div class="selfedit">
		 修改狀態
		 </div>
		</div>
	</div>
	<div class="center_column">
		<ul class="tabs">
			<li>
				<a href="#tab1">people</a>
			</li>
			<li>
				<a href="#tab2">events</a>
			</li>
		</ul>

		<div class="tab_container">
			<div id="tab1" class="tab_content">
				<% for i in 1..80 %>
				<%= image_tag("profile#{i%4}.jpg", :class => "result_photo") %>
				<% end %>
			</div>
			<div id="tab2" class="tab_content">
				<h2>jQuery is a new kind of JavaScript Library.</h2>
				<p>
					jQuery is a fast and concise JavaScript Library that simplifies HTML document traversing, event handling, animating, and Ajax interactions for rapid web development. jQuery is designed to change the way that you write JavaScript
				</p>
			</div>
		</div>
	</div>
	<div class="right_column">
		<ul class="tabs">
			<li>
				<a href="#tab12">people</a>
			</li>
			<li>
				<a href="#tab22">events</a>
			</li>
		</ul>

		<div class="tab_container">
			<div id="tab12" class="tab_content">
				<div>
					Travel
				</div>
				<div>
					Sport
				</div>
				<div>
					Food
				</div>
				<div>
					Club
				</div>
			</div>
			<div id="tab22" class="tab_content">
				<h2>jQuery ind </h2>

			</div>
		</div>
	</div>
</div>

app/views/main/_new_event_dialog.html.erb
<%= javascript_include_tag "dialog", "data-turbolinks-track" => true %>
<%= javascript_include_tag "http://code.jquery.com/jquery-1.9.1.js", "data-turbolinks-track" => true %>
<%= javascript_include_tag "http://code.jquery.com/ui/1.10.3/jquery-ui.js", "data-turbolinks-track" => true %>
<link data-turbolinks-track="true" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" media="all" rel="stylesheet">

<div class="dialog_translucent_background" hidden='true' style="z-index: 999999">
	<div class="dialog">
		<div class="dialog_title">
			New Event
		</div>
		<div class="dialog_content">

			<%= form_for :new_event, url: event_create_path do |f| %>
			<table class="uiInfoTable">
				<tr>
					<th class="dialg_label"> <%= f.label :title, "Name:" %></th><td>
					<div style="width: 100%;">
						<%= f.text_field :title, :class => "dialog_data" %>
					</div></td>
				</tr>
				<tr>
					<th class="dialg_label"><%= f.label :description, "Description:" %></th>
					<div style="width: 100%;">
						<td> <%= f.text_area :description, class: 'dialog_data' %>
					</div>
				</tr>
				<tr>
					<th class="dialg_label"> <%= f.label nil, "Where" %></th>
					<div style="width: 100%;">
						<td> <%= f.text_field :location , :class => "dialog_data" %> </td>
					</div>
				</tr>
				<tr>
					<th class="dialg_label"> <%= f.label nil, "Date" %></th>
					<td> <%= f.text_field :s_date, :id => 'start_datepicker' %>
					<%= f.text_field :e_date, :id => 'end_datepicker' %> </td>
				</tr>
				<tr>
					<th class="dialg_label"> <%= f.label :visibility, "Privacy" %></th><td> <%= f.select :visibility, [['public', 0], ['private', 1], ['need authority' ,2 ]] %> </td>
				</tr>
			</table>
		</div>
		<div class="dialog_footer">
			<table>
				<tr>
					<td><!-- <input class="dialog_footer_button" name="commit" type="submit" value="Save" style='padding: 0px;border: 0px;height:20px;'> --> <%= submit_tag "Save", :class=> "dialog_footer_button"%><% end %> </td>
					<td> 
					<div id="dialog_cancel" style="margin-left: 0px" class="dialog_footer_button">
						Cancel
					</div></td>
				</tr>
			</table>
		</div>
	</div>
</div>

app/views/main/_title.html.erb
<div style="height: 30px;">
	<div class="top_title">
		<div class="title_container">
			<div class="iToGo">
				<%= link_to "iTOGO","/main/home",id:"text2" %>
			</div>
			<div style="float: left;margin-top: 5px;width: 543px;margin-left: 10px;margin-right: 10px;text-align: right;">
				<%= link_to "New Event", '/main/new_event', :class =>'event_new', :remote => true, "data-type" => "script" %>
			</div>
			<div style="margin-top: 5px;" class="logout">
				<% if current_user %> welcome ,<%= current_user.name =%>
				<%= link_to('登出', destroy_user_session_path, :method => :delete) %>
				<% end %>
				<!-- <%= link_to "log out", '/', :class =>'event_new' %> -->
			</div>
		</div>
	</div>
</div>
<%= render partial: "/main/new_event_dialog" %>

app/views/main/chat.js.erb
$('.center_column .tab_container').html('<div class="center_top">\
	<div class="top_1">\
		<%= image_tag("profile1.jpg", :class => "result_photo1") %>\
	</div>\
	<div class="top_2">\
		姓名:Amay cheng\
		<br>\
		年齡:24\
		<br>\
		位置：新店\
		<br>\
		國家：台灣\
		<br>\
	</div>\
	<div class="top_4">\
		關於我：\
		<br>\
		Call me Jo...22,Malaysia born Chinese ,dark hair,dark brown eye~ Friendly,happy go lucky,easy\
	</div>\
	<div class="top_3">\
		加入最愛\
		<br>\
		刪除聊天\
		<br>\
		封鎖\
		<br>\
		檢舉\
		<br>\
	</div>\
</div>\
<div class="center_center">\
	<%= image_tag("chatpic.jpg", :class => "center_pic") %>\
</div>\
<div class="center_bottom">\
	<%= text_field(:comment, :text, :class => "chat_input", size: "74")%>\
	<div class="chat_bottom">\
		<%= submit_tag("傳送圖片")%>\
		<%= submit_tag("圖示選擇")%>\
		<%= submit_tag("傳送訊息")%>\
	</div>\
</div>\
</div>');
$('.right_column .tab_container').show();

app/views/main/events.js.erb
$('.center_column .tab_container').html('<div class="tab_content">\
	<%= link_to "New Event", '/main/new_event', :class =>'event_new', :remote => true, "data-type" => "script" %>\
				<% for i in 1..10 %>\
				<div class="events_block">\
					<div class="events_pic">\
						<%= image_tag("profile#{i%4}.jpg", :class => "result_events",) %>\
					</div>\
					<div class="events_info">\
						Amay chang\
						<br>\
						找一起出去玩的人\
						<br>\
						時間:2013.03.03 人數：20人\
						<br>\
					</div>\
					<div class="events_bottom">\
						<%= submit_tag("詳情")%>\
						<br>\
						<%= submit_tag("參加")%>\
						<br>\
						<%= submit_tag("加入觀察")%>\
						<br>\
					</div>\
				</div>\
				<% end %>\
			</div>');
			
$('li#events').addClass("active").siblings(".active").removeClass("active");
$('.right_column .tab_container').show();

app/views/main/home.html.erb
<%= render partial: "title" %>

<div class="container">
	<div class="left_column">
		<div class="top_profile">
			<%= image_tag("profile.jpg", :alt => "Norman Chen", :size => "70x70", :class => "profile_photo") %>
			<div class="profile_name">
				Norman Chen
				<br>
				<%= link_to "Edit your profile","/main/profile",class:"decoration", :remote => true, "data-type" => "script" %>
			</div>
		</div>
		<div class="tags">
			<% for i in 1..30 %>
			<%= link_to "#Sport #{i*11}", '/events/event/', :class => 'circle tag' %>
			<% end %>
		</div>
	</div>
	<div class="center_column">
		<div class="tab_container">
			<div class="tab_content">

				<% @events.each do |event| %>
				<div class="events_block">
					<div class="events_pic">
						<%= image_tag("profile#{i%4}.jpg", :class => "result_events",) %>
					</div>
					<div class="events_info">
						<div>
							<%= link_to event.title, event_path(event.id) %>
						</div>
						<div>
							<%= event.location %>
						</div>
						<div>
							<% if event.s_date != nil%>
							時間:<%= event.s_date %>
							<% end %>
							人數：20人
						</div>
					</div>
					<div class="events_bottom">
						<div>
							<%= link_to 'Join', join_path(event.id) %>
						</div>
						<div>
							<%= link_to 'Follow', '/events/event/' %>
						</div>
					</div>
				</div>
				<% end %>
			</div>
		</div>
	</div>
	<div class="right_column"></div>
</div>

app/views/main/index.html.erb
<div id="bg">
	<div id="user_nav" >
		<span id="text1">LOG IN ITOGO</span>

		<div id="sing_in_openid">
			使用快速登入．ITOGO不會公佈您任何資訊．
			<br>
			<%= link_to image_tag("fblogin.jpg", :border => 0), user_omniauth_authorize_path(:facebook) %>
		
			<%= link_to image_tag("googlelogin.jpg", :border => 0), user_omniauth_authorize_path(:google_oauth2) %>
		</div>
		
		<div id="sing_in">
			<% if current_user %>
			<%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
			<%= link_to('修改密碼', edit_registration_path(:user)) %>
			<% else %>

			<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
			<div>
				<%= f.label :email %>
				<%= f.email_field :email, :autofocus => true %>
			</div>

			<div>
				<%= f.label :password %>
				<%= f.password_field :password %>
			</div>

			<% if devise_mapping.rememberable? -%>
			<div>
				<%= f.check_box :remember_me %> <%= f.label :remember_me %>
			</div>
			<% end -%>

			<div>
				<%= f.submit "Sign in" %>
			</div>
			<% end %>

			<% if devise_mapping.registerable? && controller_name != 'registrations' %>
  			<%= link_to "Sign up", new_registration_path(resource_name) %><br />
			<% end -%>
			<% end %>
		</div>
	</div>
	<div id="index_footer">
		© 2013 OGRE STUDION
	</div>
</div>

app/views/main/map.html.erb
<h1>Main#map</h1>
<p>Find me in app/views/main/map.html.erb</p>

app/views/main/new_event.js.erb
$('.dialog_translucent_background').show();


$('.dialog').css("margin-top", ($(window).height() - $('.dialog').height()) / 2);

app/views/main/people.js.erb
$('.center_column .tab_container').html('<div class="tab_content">\
				<% for i in 1..80 %>\
				<%= image_tag("profile#{i%4}.jpg", :class => "result_photo") %>\
				<% end %>
			</div>');
$('li#people').addClass("active").siblings(".active").removeClass("active");
$('.right_column .tab_container').show();

app/views/main/profile.js.erb
$('.center_column .tab_container').html('<div class="profile_center">\
				<% for i in 1..10 %>\
				<%= image_tag("profile#{i%4}.jpg", :class => "result_photo") %>\
				<% end %>
		</div>');

$('.right_column .tab_container').hide();
		